build site:
  image: node:10.15.0
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist


# unit test:
#   image: node:6
#   stage: test
#   script:
#     - npm install --progress=false
#     - npm run unit

testdeploy:
  image: node:10.15.0
  stage: testdeploy
  script:
    - npm install
    - npm run netdev

deploy:
  image: node:10.15.0
  stage: deploy
  script:
    - npm install
    - npm run deploy