
backend:
  name: gitlab
  repo: Imaximilian/portfolio

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Summary", name: "summary", widget: "markdown", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Tags", name: "tags", widget: "list", default: ["rest"]}

  - name: "aboutme"
    label: "Aboutme"
    folder: "blog/aboutMe"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image",required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Summary", name: "summary", widget: "markdown"}

  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "blog/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Start Date", name: "startdate", widget: "date"}
      - {label: "End Date", name: "enddate", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Summary", name: "summary", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["test"]}

  - name: "education" # Used in routes, e.g., /admin/collections/blog
    label: "Education" # Used in the UI
    folder: "blog/aboutMe/education" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date", name: "startdate", widget: "date"}
      - {label: "End Date", name: "enddate", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown" }

  - name: "career" # Used in routes, e.g., /admin/collections/blog
    label: "Career" # Used in the UI
    folder: "blog/aboutMe/career" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date", name: "startdate", widget: "date"}
      - {label: "End Date", name: "enddate", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown" }