# backend:
#   name: git-gateway
#   branch: master # Branch to update (optional; defaults to master)
#   # repo: Imaximilian/portfolio
#   # auth_type: implicit # Required for implicit grant
#   # accept_roles: #optional - accepts all users if left out
#     # - admin
# media_folder: "../assets/uploads" 
# public_folder: "../assets/uploads" 
# collections:
#   - name: "blog" # Used in routes, e.g., /admin/collections/blog
#     label: "Blog" # Used in the UI
#     folder: "_posts/blog" # The path to the folder where the documents are stored
#     create: true # Allow users to create new documents in this collection
#     slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
#     fields: # The fields for each document, usually in front matter
#       - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Publish Date", name: "date", widget: "datetime"}
#       - {label: "Featured Image", name: "thumbnail", widget: "image"}
#       - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}


backend:
  name: gitlab
  repo: Imaximilian/portfolio

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Footer", name: "footer", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}

